
/*-----------------------------------------------------------------------------
	Basic OpenGL 1.1 functions
-----------------------------------------------------------------------------*/

GL_EXT(_GL)
// OpenGL 1.1
GL_FNC(_GL,void,glAccum,(GLenum,GLfloat))
GL_FNC(_GL,void,glAlphaFunc,(GLenum,GLclampf))
GL_FNC(_GL,GLboolean,glAreTexturesResident,(GLsizei,const GLuint*,GLboolean*))
GL_FNC(_GL,void,glArrayElement,(GLint))
GL_FNC(_GL,void,glBegin,(GLenum))
GL_FNC(_GL,void,glBindTexture,(GLenum,GLuint))
GL_FNC(_GL,void,glBitmap,(GLsizei,GLsizei,GLfloat,GLfloat,GLfloat,GLfloat,const GLubyte*))
GL_FNC(_GL,void,glBlendFunc,(GLenum,GLenum))
GL_FNC(_GL,void,glCallList,(GLuint))
GL_FNC(_GL,void,glCallLists,(GLsizei,GLenum,const GLvoid*))
GL_FNC(_GL,void,glClear,(GLbitfield))
GL_FNC(_GL,void,glClearAccum,(GLfloat,GLfloat,GLfloat,GLfloat))
GL_FNC(_GL,void,glClearColor,(GLclampf,GLclampf,GLclampf,GLclampf))
GL_FNC(_GL,void,glClearDepth,(GLclampd))
GL_FNC(_GL,void,glClearIndex,(GLfloat))
GL_FNC(_GL,void,glClearStencil,(GLint))
GL_FNC(_GL,void,glClipPlane,(GLenum,const GLdouble*))
GL_FNC(_GL,void,glColor3b,(GLbyte,GLbyte,GLbyte))
GL_FNC(_GL,void,glColor3bv,(const GLbyte*))
GL_FNC(_GL,void,glColor3d,(GLdouble,GLdouble,GLdouble))
GL_FNC(_GL,void,glColor3dv,(const GLdouble*))
GL_FNC(_GL,void,glColor3f,(GLfloat,GLfloat,GLfloat))
GL_FNC(_GL,void,glColor3fv,(const GLfloat*))
GL_FNC(_GL,void,glColor3i,(GLint,GLint,GLint))
GL_FNC(_GL,void,glColor3iv,(const GLint*))
GL_FNC(_GL,void,glColor3s,(GLshort,GLshort,GLshort))
GL_FNC(_GL,void,glColor3sv,(const GLshort*))
GL_FNC(_GL,void,glColor3ub,(GLubyte,GLubyte,GLubyte))
GL_FNC(_GL,void,glColor3ubv,(const GLubyte*))
GL_FNC(_GL,void,glColor3ui,(GLuint,GLuint,GLuint))
GL_FNC(_GL,void,glColor3uiv,(const GLuint*))
GL_FNC(_GL,void,glColor3us,(GLushort,GLushort,GLushort))
GL_FNC(_GL,void,glColor3usv,(const GLushort*))
GL_FNC(_GL,void,glColor4b,(GLbyte,GLbyte,GLbyte,GLbyte))
GL_FNC(_GL,void,glColor4bv,(const GLbyte*))
GL_FNC(_GL,void,glColor4d,(GLdouble,GLdouble,GLdouble,GLdouble))
GL_FNC(_GL,void,glColor4dv,(const GLdouble*))
GL_FNC(_GL,void,glColor4f,(GLfloat,GLfloat,GLfloat,GLfloat))
GL_FNC(_GL,void,glColor4fv,(const GLfloat*))
GL_FNC(_GL,void,glColor4i,(GLint,GLint,GLint,GLint))
GL_FNC(_GL,void,glColor4iv,(const GLint*))
GL_FNC(_GL,void,glColor4s,(GLshort,GLshort,GLshort,GLshort))
GL_FNC(_GL,void,glColor4sv,(const GLshort*))
GL_FNC(_GL,void,glColor4ub,(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha))
GL_FNC(_GL,void,glColor4ubv,(const GLubyte *v))
GL_FNC(_GL,void,glColor4ui,(GLuint red, GLuint green, GLuint blue, GLuint alpha))
GL_FNC(_GL,void,glColor4uiv,(const GLuint *v))
GL_FNC(_GL,void,glColor4us,(GLushort red, GLushort green, GLushort blue, GLushort alpha))
GL_FNC(_GL,void,glColor4usv,(const GLushort *v))
GL_FNC(_GL,void,glColorMask,(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))
GL_FNC(_GL,void,glColorMaterial,(GLenum face, GLenum mode))
GL_FNC(_GL,void,glColorPointer,(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer))
GL_FNC(_GL,void,glCopyPixels,(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type))
GL_FNC(_GL,void,glCopyTexImage1D,(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border))
GL_FNC(_GL,void,glCopyTexImage2D,(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border))
GL_FNC(_GL,void,glCopyTexSubImage1D,(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width))
GL_FNC(_GL,void,glCopyTexSubImage2D,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height))
GL_FNC(_GL,void,glCullFace,(GLenum mode))
GL_FNC(_GL,void,glDeleteLists,(GLuint list, GLsizei range))
GL_FNC(_GL,void,glDeleteTextures,(GLsizei n, const GLuint *textures))
GL_FNC(_GL,void,glDepthFunc,(GLenum func))
GL_FNC(_GL,void,glDepthMask,(GLboolean flag))
GL_FNC(_GL,void,glDepthRange,(GLclampd zNear, GLclampd zFar))
GL_FNC(_GL,void,glDisable,(GLenum cap))
GL_FNC(_GL,void,glDisableClientState,(GLenum array))
GL_FNC(_GL,void,glDrawArrays,(GLenum mode, GLint first, GLsizei count))
GL_FNC(_GL,void,glDrawBuffer,(GLenum mode))
GL_FNC(_GL,void,glDrawElements,(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices))
GL_FNC(_GL,void,glDrawPixels,(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels))
GL_FNC(_GL,void,glEdgeFlag,(GLboolean flag))
GL_FNC(_GL,void,glEdgeFlagPointer,(GLsizei stride, const GLvoid *pointer))
GL_FNC(_GL,void,glEdgeFlagv,(const GLboolean *flag))
GL_FNC(_GL,void,glEnable,(GLenum cap))
GL_FNC(_GL,void,glEnableClientState,(GLenum array))
GL_FNC(_GL,void,glEnd,(void))
GL_FNC(_GL,void,glEndList,(void))
GL_FNC(_GL,void,glEvalCoord1d,(GLdouble u))
GL_FNC(_GL,void,glEvalCoord1dv,(const GLdouble *u))
GL_FNC(_GL,void,glEvalCoord1f,(GLfloat u))
GL_FNC(_GL,void,glEvalCoord1fv,(const GLfloat *u))
GL_FNC(_GL,void,glEvalCoord2d,(GLdouble u, GLdouble v))
GL_FNC(_GL,void,glEvalCoord2dv,(const GLdouble *u))
GL_FNC(_GL,void,glEvalCoord2f,(GLfloat u, GLfloat v))
GL_FNC(_GL,void,glEvalCoord2fv,(const GLfloat *u))
GL_FNC(_GL,void,glEvalMesh1,(GLenum mode, GLint i1, GLint i2))
GL_FNC(_GL,void,glEvalMesh2,(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2))
GL_FNC(_GL,void,glEvalPoint1,(GLint i))
GL_FNC(_GL,void,glEvalPoint2,(GLint i, GLint j))
GL_FNC(_GL,void,glFeedbackBuffer,(GLsizei size, GLenum type, GLfloat *buffer))
GL_FNC(_GL,void,glFinish,(void))
GL_FNC(_GL,void,glFlush,(void))
GL_FNC(_GL,void,glFogf,(GLenum pname, GLfloat param))
GL_FNC(_GL,void,glFogfv,(GLenum pname, const GLfloat *params))
GL_FNC(_GL,void,glFogi,(GLenum pname, GLint param))
GL_FNC(_GL,void,glFogiv,(GLenum pname, const GLint *params))
GL_FNC(_GL,void,glFrontFace,(GLenum mode))
GL_FNC(_GL,void,glFrustum,(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar))
GL_FNC(_GL,GLuint,glGenLists,(GLsizei range))
GL_FNC(_GL,void,glGenTextures,(GLsizei n, GLuint *textures))
GL_FNC(_GL,void,glGetBooleanv,(GLenum pname, GLboolean *params))
GL_FNC(_GL,void,glGetClipPlane,(GLenum plane, GLdouble *equation))
GL_FNC(_GL,void,glGetDoublev,(GLenum pname, GLdouble *params))
GL_FNC(_GL,GLenum,glGetError,(void))
GL_FNC(_GL,void,glGetFloatv,(GLenum pname, GLfloat *params))
GL_FNC(_GL,void,glGetIntegerv,(GLenum pname, GLint *params))
GL_FNC(_GL,void,glGetLightfv,(GLenum light, GLenum pname, GLfloat *params))
GL_FNC(_GL,void,glGetLightiv,(GLenum light, GLenum pname, GLint *params))
GL_FNC(_GL,void,glGetMapdv,(GLenum target, GLenum query, GLdouble *v))
GL_FNC(_GL,void,glGetMapfv,(GLenum target, GLenum query, GLfloat *v))
GL_FNC(_GL,void,glGetMapiv,(GLenum target, GLenum query, GLint *v))
GL_FNC(_GL,void,glGetMaterialfv,(GLenum face, GLenum pname, GLfloat *params))
GL_FNC(_GL,void,glGetMaterialiv,(GLenum face, GLenum pname, GLint *params))
GL_FNC(_GL,void,glGetPixelMapfv,(GLenum map, GLfloat *values))
GL_FNC(_GL,void,glGetPixelMapuiv,(GLenum map, GLuint *values))
GL_FNC(_GL,void,glGetPixelMapusv,(GLenum map, GLushort *values))
GL_FNC(_GL,void,glGetPointerv,(GLenum pname, GLvoid* *params))
GL_FNC(_GL,void,glGetPolygonStipple,(GLubyte *mask))
GL_FNC(_GL,const GLubyte *,glGetString,(GLenum name))
GL_FNC(_GL,void,glGetTexEnvfv,(GLenum target, GLenum pname, GLfloat *params))
GL_FNC(_GL,void,glGetTexEnviv,(GLenum target, GLenum pname, GLint *params))
GL_FNC(_GL,void,glGetTexGendv,(GLenum coord, GLenum pname, GLdouble *params))
GL_FNC(_GL,void,glGetTexGenfv,(GLenum coord, GLenum pname, GLfloat *params))
GL_FNC(_GL,void,glGetTexGeniv,(GLenum coord, GLenum pname, GLint *params))
GL_FNC(_GL,void,glGetTexImage,(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels))
GL_FNC(_GL,void,glGetTexLevelParameterfv,(GLenum target, GLint level, GLenum pname, GLfloat *params))
GL_FNC(_GL,void,glGetTexLevelParameteriv,(GLenum target, GLint level, GLenum pname, GLint *params))
GL_FNC(_GL,void,glGetTexParameterfv,(GLenum target, GLenum pname, GLfloat *params))
GL_FNC(_GL,void,glGetTexParameteriv,(GLenum target, GLenum pname, GLint *params))
GL_FNC(_GL,void,glHint,(GLenum target, GLenum mode))
GL_FNC(_GL,void,glIndexMask,(GLuint mask))
GL_FNC(_GL,void,glIndexPointer,(GLenum type, GLsizei stride, const GLvoid *pointer))
GL_FNC(_GL,void,glIndexd,(GLdouble c))
GL_FNC(_GL,void,glIndexdv,(const GLdouble *c))
GL_FNC(_GL,void,glIndexf,(GLfloat c))
GL_FNC(_GL,void,glIndexfv,(const GLfloat *c))
GL_FNC(_GL,void,glIndexi,(GLint c))
GL_FNC(_GL,void,glIndexiv,(const GLint *c))
GL_FNC(_GL,void,glIndexs,(GLshort c))
GL_FNC(_GL,void,glIndexsv,(const GLshort *c))
GL_FNC(_GL,void,glIndexub,(GLubyte c))
GL_FNC(_GL,void,glIndexubv,(const GLubyte *c))
GL_FNC(_GL,void,glInitNames,(void))
GL_FNC(_GL,void,glInterleavedArrays,(GLenum format, GLsizei stride, const GLvoid *pointer))
GL_FNC(_GL,GLboolean,glIsEnabled,(GLenum cap))
GL_FNC(_GL,GLboolean,glIsList,(GLuint list))
GL_FNC(_GL,GLboolean,glIsTexture,(GLuint texture))
GL_FNC(_GL,void,glLightModelf,(GLenum pname, GLfloat param))
GL_FNC(_GL,void,glLightModelfv,(GLenum pname, const GLfloat *params))
GL_FNC(_GL,void,glLightModeli,(GLenum pname, GLint param))
GL_FNC(_GL,void,glLightModeliv,(GLenum pname, const GLint *params))
GL_FNC(_GL,void,glLightf,(GLenum light, GLenum pname, GLfloat param))
GL_FNC(_GL,void,glLightfv,(GLenum light, GLenum pname, const GLfloat *params))
GL_FNC(_GL,void,glLighti,(GLenum light, GLenum pname, GLint param))
GL_FNC(_GL,void,glLightiv,(GLenum light, GLenum pname, const GLint *params))
GL_FNC(_GL,void,glLineStipple,(GLint factor, GLushort pattern))
GL_FNC(_GL,void,glLineWidth,(GLfloat width))
GL_FNC(_GL,void,glListBase,(GLuint base))
GL_FNC(_GL,void,glLoadIdentity,(void))
GL_FNC(_GL,void,glLoadMatrixd,(const GLdouble *m))
GL_FNC(_GL,void,glLoadMatrixf,(const GLfloat *m))
GL_FNC(_GL,void,glLoadName,(GLuint name))
GL_FNC(_GL,void,glLogicOp,(GLenum opcode))
GL_FNC(_GL,void,glMap1d,(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points))
GL_FNC(_GL,void,glMap1f,(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points))
GL_FNC(_GL,void,glMap2d,(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points))
GL_FNC(_GL,void,glMap2f,(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points))
GL_FNC(_GL,void,glMapGrid1d,(GLint un, GLdouble u1, GLdouble u2))
GL_FNC(_GL,void,glMapGrid1f,(GLint un, GLfloat u1, GLfloat u2))
GL_FNC(_GL,void,glMapGrid2d,(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2))
GL_FNC(_GL,void,glMapGrid2f,(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2))
GL_FNC(_GL,void,glMaterialf,(GLenum face, GLenum pname, GLfloat param))
GL_FNC(_GL,void,glMaterialfv,(GLenum face, GLenum pname, const GLfloat *params))
GL_FNC(_GL,void,glMateriali,(GLenum face, GLenum pname, GLint param))
GL_FNC(_GL,void,glMaterialiv,(GLenum face, GLenum pname, const GLint *params))
GL_FNC(_GL,void,glMatrixMode,(GLenum mode))
GL_FNC(_GL,void,glMultMatrixd,(const GLdouble *m))
GL_FNC(_GL,void,glMultMatrixf,(const GLfloat *m))
GL_FNC(_GL,void,glNewList,(GLuint list, GLenum mode))
GL_FNC(_GL,void,glNormal3b,(GLbyte nx, GLbyte ny, GLbyte nz))
GL_FNC(_GL,void,glNormal3bv,(const GLbyte *v))
GL_FNC(_GL,void,glNormal3d,(GLdouble nx, GLdouble ny, GLdouble nz))
GL_FNC(_GL,void,glNormal3dv,(const GLdouble *v))
GL_FNC(_GL,void,glNormal3f,(GLfloat nx, GLfloat ny, GLfloat nz))
GL_FNC(_GL,void,glNormal3fv,(const GLfloat *v))
GL_FNC(_GL,void,glNormal3i,(GLint nx, GLint ny, GLint nz))
GL_FNC(_GL,void,glNormal3iv,(const GLint *v))
GL_FNC(_GL,void,glNormal3s,(GLshort nx, GLshort ny, GLshort nz))
GL_FNC(_GL,void,glNormal3sv,(const GLshort *v))
GL_FNC(_GL,void,glNormalPointer,(GLenum type, GLsizei stride, const GLvoid *pointer))
GL_FNC(_GL,void,glOrtho,(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar))
GL_FNC(_GL,void,glPassThrough,(GLfloat token))
GL_FNC(_GL,void,glPixelMapfv,(GLenum map, GLsizei mapsize, const GLfloat *values))
GL_FNC(_GL,void,glPixelMapuiv,(GLenum map, GLsizei mapsize, const GLuint *values))
GL_FNC(_GL,void,glPixelMapusv,(GLenum map, GLsizei mapsize, const GLushort *values))
GL_FNC(_GL,void,glPixelStoref,(GLenum pname, GLfloat param))
GL_FNC(_GL,void,glPixelStorei,(GLenum pname, GLint param))
GL_FNC(_GL,void,glPixelTransferf,(GLenum pname, GLfloat param))
GL_FNC(_GL,void,glPixelTransferi,(GLenum pname, GLint param))
GL_FNC(_GL,void,glPixelZoom,(GLfloat xfactor, GLfloat yfactor))
GL_FNC(_GL,void,glPointSize,(GLfloat size))
GL_FNC(_GL,void,glPolygonMode,(GLenum face, GLenum mode))
GL_FNC(_GL,void,glPolygonOffset,(GLfloat factor, GLfloat units))
GL_FNC(_GL,void,glPolygonStipple,(const GLubyte *mask))
GL_FNC(_GL,void,glPopAttrib,(void))
GL_FNC(_GL,void,glPopClientAttrib,(void))
GL_FNC(_GL,void,glPopMatrix,(void))
GL_FNC(_GL,void,glPopName,(void))
GL_FNC(_GL,void,glPrioritizeTextures,(GLsizei n, const GLuint *textures, const GLclampf *priorities))
GL_FNC(_GL,void,glPushAttrib,(GLbitfield mask))
GL_FNC(_GL,void,glPushClientAttrib,(GLbitfield mask))
GL_FNC(_GL,void,glPushMatrix,(void))
GL_FNC(_GL,void,glPushName,(GLuint name))
GL_FNC(_GL,void,glRasterPos2d,(GLdouble x, GLdouble y))
GL_FNC(_GL,void,glRasterPos2dv,(const GLdouble *v))
GL_FNC(_GL,void,glRasterPos2f,(GLfloat x, GLfloat y))
GL_FNC(_GL,void,glRasterPos2fv,(const GLfloat *v))
GL_FNC(_GL,void,glRasterPos2i,(GLint x, GLint y))
GL_FNC(_GL,void,glRasterPos2iv,(const GLint *v))
GL_FNC(_GL,void,glRasterPos2s,(GLshort x, GLshort y))
GL_FNC(_GL,void,glRasterPos2sv,(const GLshort *v))
GL_FNC(_GL,void,glRasterPos3d,(GLdouble x, GLdouble y, GLdouble z))
GL_FNC(_GL,void,glRasterPos3dv,(const GLdouble *v))
GL_FNC(_GL,void,glRasterPos3f,(GLfloat x, GLfloat y, GLfloat z))
GL_FNC(_GL,void,glRasterPos3fv,(const GLfloat *v))
GL_FNC(_GL,void,glRasterPos3i,(GLint x, GLint y, GLint z))
GL_FNC(_GL,void,glRasterPos3iv,(const GLint *v))
GL_FNC(_GL,void,glRasterPos3s,(GLshort x, GLshort y, GLshort z))
GL_FNC(_GL,void,glRasterPos3sv,(const GLshort *v))
GL_FNC(_GL,void,glRasterPos4d,(GLdouble x, GLdouble y, GLdouble z, GLdouble w))
GL_FNC(_GL,void,glRasterPos4dv,(const GLdouble *v))
GL_FNC(_GL,void,glRasterPos4f,(GLfloat x, GLfloat y, GLfloat z, GLfloat w))
GL_FNC(_GL,void,glRasterPos4fv,(const GLfloat *v))
GL_FNC(_GL,void,glRasterPos4i,(GLint x, GLint y, GLint z, GLint w))
GL_FNC(_GL,void,glRasterPos4iv,(const GLint *v))
GL_FNC(_GL,void,glRasterPos4s,(GLshort x, GLshort y, GLshort z, GLshort w))
GL_FNC(_GL,void,glRasterPos4sv,(const GLshort *v))
GL_FNC(_GL,void,glReadBuffer,(GLenum mode))
GL_FNC(_GL,void,glReadPixels,(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels))
GL_FNC(_GL,void,glRectd,(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2))
GL_FNC(_GL,void,glRectdv,(const GLdouble *v1, const GLdouble *v2))
GL_FNC(_GL,void,glRectf,(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2))
GL_FNC(_GL,void,glRectfv,(const GLfloat *v1, const GLfloat *v2))
GL_FNC(_GL,void,glRecti,(GLint x1, GLint y1, GLint x2, GLint y2))
GL_FNC(_GL,void,glRectiv,(const GLint *v1, const GLint *v2))
GL_FNC(_GL,void,glRects,(GLshort x1, GLshort y1, GLshort x2, GLshort y2))
GL_FNC(_GL,void,glRectsv,(const GLshort *v1, const GLshort *v2))
GL_FNC(_GL,GLint,glRenderMode,(GLenum mode))
GL_FNC(_GL,void,glRotated,(GLdouble angle, GLdouble x, GLdouble y, GLdouble z))
GL_FNC(_GL,void,glRotatef,(GLfloat angle, GLfloat x, GLfloat y, GLfloat z))
GL_FNC(_GL,void,glScaled,(GLdouble x, GLdouble y, GLdouble z))
GL_FNC(_GL,void,glScalef,(GLfloat x, GLfloat y, GLfloat z))
GL_FNC(_GL,void,glScissor,(GLint x, GLint y, GLsizei width, GLsizei height))
GL_FNC(_GL,void,glSelectBuffer,(GLsizei size, GLuint *buffer))
GL_FNC(_GL,void,glShadeModel,(GLenum mode))
GL_FNC(_GL,void,glStencilFunc,(GLenum func, GLint ref, GLuint mask))
GL_FNC(_GL,void,glStencilMask,(GLuint mask))
GL_FNC(_GL,void,glStencilOp,(GLenum fail, GLenum zfail, GLenum zpass))
GL_FNC(_GL,void,glTexCoord1d,(GLdouble s))
GL_FNC(_GL,void,glTexCoord1dv,(const GLdouble *v))
GL_FNC(_GL,void,glTexCoord1f,(GLfloat s))
GL_FNC(_GL,void,glTexCoord1fv,(const GLfloat *v))
GL_FNC(_GL,void,glTexCoord1i,(GLint s))
GL_FNC(_GL,void,glTexCoord1iv,(const GLint *v))
GL_FNC(_GL,void,glTexCoord1s,(GLshort s))
GL_FNC(_GL,void,glTexCoord1sv,(const GLshort *v))
GL_FNC(_GL,void,glTexCoord2d,(GLdouble s, GLdouble t))
GL_FNC(_GL,void,glTexCoord2dv,(const GLdouble *v))
GL_FNC(_GL,void,glTexCoord2f,(GLfloat s, GLfloat t))
GL_FNC(_GL,void,glTexCoord2fv,(const GLfloat *v))
GL_FNC(_GL,void,glTexCoord2i,(GLint s, GLint t))
GL_FNC(_GL,void,glTexCoord2iv,(const GLint *v))
GL_FNC(_GL,void,glTexCoord2s,(GLshort s, GLshort t))
GL_FNC(_GL,void,glTexCoord2sv,(const GLshort *v))
GL_FNC(_GL,void,glTexCoord3d,(GLdouble s, GLdouble t, GLdouble r))
GL_FNC(_GL,void,glTexCoord3dv,(const GLdouble *v))
GL_FNC(_GL,void,glTexCoord3f,(GLfloat s, GLfloat t, GLfloat r))
GL_FNC(_GL,void,glTexCoord3fv,(const GLfloat *v))
GL_FNC(_GL,void,glTexCoord3i,(GLint s, GLint t, GLint r))
GL_FNC(_GL,void,glTexCoord3iv,(const GLint *v))
GL_FNC(_GL,void,glTexCoord3s,(GLshort s, GLshort t, GLshort r))
GL_FNC(_GL,void,glTexCoord3sv,(const GLshort *v))
GL_FNC(_GL,void,glTexCoord4d,(GLdouble s, GLdouble t, GLdouble r, GLdouble q))
GL_FNC(_GL,void,glTexCoord4dv,(const GLdouble *v))
GL_FNC(_GL,void,glTexCoord4f,(GLfloat s, GLfloat t, GLfloat r, GLfloat q))
GL_FNC(_GL,void,glTexCoord4fv,(const GLfloat *v))
GL_FNC(_GL,void,glTexCoord4i,(GLint s, GLint t, GLint r, GLint q))
GL_FNC(_GL,void,glTexCoord4iv,(const GLint *v))
GL_FNC(_GL,void,glTexCoord4s,(GLshort s, GLshort t, GLshort r, GLshort q))
GL_FNC(_GL,void,glTexCoord4sv,(const GLshort *v))
GL_FNC(_GL,void,glTexCoordPointer,(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer))
GL_FNC(_GL,void,glTexEnvf,(GLenum target, GLenum pname, GLfloat param))
GL_FNC(_GL,void,glTexEnvfv,(GLenum target, GLenum pname, const GLfloat *params))
GL_FNC(_GL,void,glTexEnvi,(GLenum target, GLenum pname, GLint param))
GL_FNC(_GL,void,glTexEnviv,(GLenum target, GLenum pname, const GLint *params))
GL_FNC(_GL,void,glTexGend,(GLenum coord, GLenum pname, GLdouble param))
GL_FNC(_GL,void,glTexGendv,(GLenum coord, GLenum pname, const GLdouble *params))
GL_FNC(_GL,void,glTexGenf,(GLenum coord, GLenum pname, GLfloat param))
GL_FNC(_GL,void,glTexGenfv,(GLenum coord, GLenum pname, const GLfloat *params))
GL_FNC(_GL,void,glTexGeni,(GLenum coord, GLenum pname, GLint param))
GL_FNC(_GL,void,glTexGeniv,(GLenum coord, GLenum pname, const GLint *params))
GL_FNC(_GL,void,glTexImage1D,(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels))
GL_FNC(_GL,void,glTexImage2D,(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels))
GL_FNC(_GL,void,glTexParameterf,(GLenum target, GLenum pname, GLfloat param))
GL_FNC(_GL,void,glTexParameterfv,(GLenum target, GLenum pname, const GLfloat *params))
GL_FNC(_GL,void,glTexParameteri,(GLenum target, GLenum pname, GLint param))
GL_FNC(_GL,void,glTexParameteriv,(GLenum target, GLenum pname, const GLint *params))
GL_FNC(_GL,void,glTexSubImage1D,(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels))
GL_FNC(_GL,void,glTexSubImage2D,(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels))
GL_FNC(_GL,void,glTranslated,(GLdouble x, GLdouble y, GLdouble z))
GL_FNC(_GL,void,glTranslatef,(GLfloat x, GLfloat y, GLfloat z))
GL_FNC(_GL,void,glVertex2d,(GLdouble x, GLdouble y))
GL_FNC(_GL,void,glVertex2dv,(const GLdouble *v))
GL_FNC(_GL,void,glVertex2f,(GLfloat x, GLfloat y))
GL_FNC(_GL,void,glVertex2fv,(const GLfloat *v))
GL_FNC(_GL,void,glVertex2i,(GLint x, GLint y))
GL_FNC(_GL,void,glVertex2iv,(const GLint *v))
GL_FNC(_GL,void,glVertex2s,(GLshort x, GLshort y))
GL_FNC(_GL,void,glVertex2sv,(const GLshort *v))
GL_FNC(_GL,void,glVertex3d,(GLdouble x, GLdouble y, GLdouble z))
GL_FNC(_GL,void,glVertex3dv,(const GLdouble *v))
GL_FNC(_GL,void,glVertex3f,(GLfloat x, GLfloat y, GLfloat z))
GL_FNC(_GL,void,glVertex3fv,(const GLfloat *v))
GL_FNC(_GL,void,glVertex3i,(GLint x, GLint y, GLint z))
GL_FNC(_GL,void,glVertex3iv,(const GLint *v))
GL_FNC(_GL,void,glVertex3s,(GLshort x, GLshort y, GLshort z))
GL_FNC(_GL,void,glVertex3sv,(const GLshort *v))
GL_FNC(_GL,void,glVertex4d,(GLdouble x, GLdouble y, GLdouble z, GLdouble w))
GL_FNC(_GL,void,glVertex4dv,(const GLdouble *v))
GL_FNC(_GL,void,glVertex4f,(GLfloat x, GLfloat y, GLfloat z, GLfloat w))
GL_FNC(_GL,void,glVertex4fv,(const GLfloat *v))
GL_FNC(_GL,void,glVertex4i,(GLint x, GLint y, GLint z, GLint w))
GL_FNC(_GL,void,glVertex4iv,(const GLint *v))
GL_FNC(_GL,void,glVertex4s,(GLshort x, GLshort y, GLshort z, GLshort w))
GL_FNC(_GL,void,glVertex4sv,(const GLshort *v))
GL_FNC(_GL,void,glVertexPointer,(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer))
GL_FNC(_GL,void,glViewport,(GLint x, GLint y, GLsizei width, GLsizei height))

/*-----------------------------------------------------------------------------
	Basic OpenGL 1.2 functions
-----------------------------------------------------------------------------*/

GL_EXT(_GL_1_2)
// GL 1.2
GL_FNC(_GL_1_2,void,glBlendColor,(GLclampf, GLclampf, GLclampf, GLclampf))
GL_FNC(_GL_1_2,void,glBlendEquation,(GLenum))
GL_FNC(_GL_1_2,void,glDrawRangeElements,(GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *))
GL_FNC(_GL_1_2,void,glColorTable,(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *))
GL_FNC(_GL_1_2,void,glColorTableParameterfv,(GLenum, GLenum, const GLfloat *))
GL_FNC(_GL_1_2,void,glColorTableParameteriv,(GLenum, GLenum, const GLint *))
GL_FNC(_GL_1_2,void,glCopyColorTable,(GLenum, GLenum, GLint, GLint, GLsizei))
GL_FNC(_GL_1_2,void,glGetColorTable,(GLenum, GLenum, GLenum, GLvoid *))
GL_FNC(_GL_1_2,void,glGetColorTableParameterfv,(GLenum, GLenum, GLfloat *))
GL_FNC(_GL_1_2,void,glGetColorTableParameteriv,(GLenum, GLenum, GLint *))
GL_FNC(_GL_1_2,void,glColorSubTable,(GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *))
GL_FNC(_GL_1_2,void,glCopyColorSubTable,(GLenum, GLsizei, GLint, GLint, GLsizei))
GL_FNC(_GL_1_2,void,glConvolutionFilter1D,(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *))
GL_FNC(_GL_1_2,void,glConvolutionFilter2D,(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *))
GL_FNC(_GL_1_2,void,glConvolutionParameterf,(GLenum, GLenum, GLfloat))
GL_FNC(_GL_1_2,void,glConvolutionParameterfv,(GLenum, GLenum, const GLfloat *))
GL_FNC(_GL_1_2,void,glConvolutionParameteri,(GLenum, GLenum, GLint))
GL_FNC(_GL_1_2,void,glConvolutionParameteriv,(GLenum, GLenum, const GLint *))
GL_FNC(_GL_1_2,void,glCopyConvolutionFilter1D,(GLenum, GLenum, GLint, GLint, GLsizei))
GL_FNC(_GL_1_2,void,glCopyConvolutionFilter2D,(GLenum, GLenum, GLint, GLint, GLsizei, GLsizei))
GL_FNC(_GL_1_2,void,glGetConvolutionFilter,(GLenum, GLenum, GLenum, GLvoid *))
GL_FNC(_GL_1_2,void,glGetConvolutionParameterfv,(GLenum, GLenum, GLfloat *))
GL_FNC(_GL_1_2,void,glGetConvolutionParameteriv,(GLenum, GLenum, GLint *))
GL_FNC(_GL_1_2,void,glGetSeparableFilter,(GLenum, GLenum, GLenum, GLvoid *, GLvoid *, GLvoid *))
GL_FNC(_GL_1_2,void,glSeparableFilter2D,(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *))
GL_FNC(_GL_1_2,void,glGetHistogram,(GLenum, GLboolean, GLenum, GLenum, GLvoid *))
GL_FNC(_GL_1_2,void,glGetHistogramParameterfv,(GLenum, GLenum, GLfloat *))
GL_FNC(_GL_1_2,void,glGetHistogramParameteriv,(GLenum, GLenum, GLint *))
GL_FNC(_GL_1_2,void,glGetMinmax,(GLenum, GLboolean, GLenum, GLenum, GLvoid *))
GL_FNC(_GL_1_2,void,glGetMinmaxParameterfv,(GLenum, GLenum, GLfloat *))
GL_FNC(_GL_1_2,void,glGetMinmaxParameteriv,(GLenum, GLenum, GLint *))
GL_FNC(_GL_1_2,void,glHistogram,(GLenum, GLsizei, GLenum, GLboolean))
GL_FNC(_GL_1_2,void,glMinmax,(GLenum, GLenum, GLboolean))
GL_FNC(_GL_1_2,void,glResetHistogram,(GLenum))
GL_FNC(_GL_1_2,void,glResetMinmax,(GLenum))
GL_FNC(_GL_1_2,void,glTexImage3D,(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *))
GL_FNC(_GL_1_2,void,glTexSubImage3D,(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *))
GL_FNC(_GL_1_2,void,glCopyTexSubImage3D,(GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei))

/*-----------------------------------------------------------------------------
	Basic OpenGL 1.3 functions
-----------------------------------------------------------------------------*/

GL_EXT(_GL_1_3)
// GL 1.3
GL_FNC(_GL_1_3,void,glActiveTexture,(GLenum))
GL_FNC(_GL_1_3,void,glClientActiveTexture,(GLenum))
GL_FNC(_GL_1_3,void,glMultiTexCoord1d,(GLenum, GLdouble))
GL_FNC(_GL_1_3,void,glMultiTexCoord1dv,(GLenum, const GLdouble *))
GL_FNC(_GL_1_3,void,glMultiTexCoord1f,(GLenum, GLfloat))
GL_FNC(_GL_1_3,void,glMultiTexCoord1fv,(GLenum, const GLfloat *))
GL_FNC(_GL_1_3,void,glMultiTexCoord1i,(GLenum, GLint))
GL_FNC(_GL_1_3,void,glMultiTexCoord1iv,(GLenum, const GLint *))
GL_FNC(_GL_1_3,void,glMultiTexCoord1s,(GLenum, GLshort))
GL_FNC(_GL_1_3,void,glMultiTexCoord1sv,(GLenum, const GLshort *))
GL_FNC(_GL_1_3,void,glMultiTexCoord2d,(GLenum, GLdouble, GLdouble))
GL_FNC(_GL_1_3,void,glMultiTexCoord2dv,(GLenum, const GLdouble *))
GL_FNC(_GL_1_3,void,glMultiTexCoord2f,(GLenum, GLfloat, GLfloat))
GL_FNC(_GL_1_3,void,glMultiTexCoord2fv,(GLenum, const GLfloat *))
GL_FNC(_GL_1_3,void,glMultiTexCoord2i,(GLenum, GLint, GLint))
GL_FNC(_GL_1_3,void,glMultiTexCoord2iv,(GLenum, const GLint *))
GL_FNC(_GL_1_3,void,glMultiTexCoord2s,(GLenum, GLshort, GLshort))
GL_FNC(_GL_1_3,void,glMultiTexCoord2sv,(GLenum, const GLshort *))
GL_FNC(_GL_1_3,void,glMultiTexCoord3d,(GLenum, GLdouble, GLdouble, GLdouble))
GL_FNC(_GL_1_3,void,glMultiTexCoord3dv,(GLenum, const GLdouble *))
GL_FNC(_GL_1_3,void,glMultiTexCoord3f,(GLenum, GLfloat, GLfloat, GLfloat))
GL_FNC(_GL_1_3,void,glMultiTexCoord3fv,(GLenum, const GLfloat *))
GL_FNC(_GL_1_3,void,glMultiTexCoord3i,(GLenum, GLint, GLint, GLint))
GL_FNC(_GL_1_3,void,glMultiTexCoord3iv,(GLenum, const GLint *))
GL_FNC(_GL_1_3,void,glMultiTexCoord3s,(GLenum, GLshort, GLshort, GLshort))
GL_FNC(_GL_1_3,void,glMultiTexCoord3sv,(GLenum, const GLshort *))
GL_FNC(_GL_1_3,void,glMultiTexCoord4d,(GLenum, GLdouble, GLdouble, GLdouble, GLdouble))
GL_FNC(_GL_1_3,void,glMultiTexCoord4dv,(GLenum, const GLdouble *))
GL_FNC(_GL_1_3,void,glMultiTexCoord4f,(GLenum, GLfloat, GLfloat, GLfloat, GLfloat))
GL_FNC(_GL_1_3,void,glMultiTexCoord4fv,(GLenum, const GLfloat *))
GL_FNC(_GL_1_3,void,glMultiTexCoord4i,(GLenum, GLint, GLint, GLint, GLint))
GL_FNC(_GL_1_3,void,glMultiTexCoord4iv,(GLenum, const GLint *))
GL_FNC(_GL_1_3,void,glMultiTexCoord4s,(GLenum, GLshort, GLshort, GLshort, GLshort))
GL_FNC(_GL_1_3,void,glMultiTexCoord4sv,(GLenum, const GLshort *))
GL_FNC(_GL_1_3,void,glLoadTransposeMatrixf,(const GLfloat *))
GL_FNC(_GL_1_3,void,glLoadTransposeMatrixd,(const GLdouble *))
GL_FNC(_GL_1_3,void,glMultTransposeMatrixf,(const GLfloat *))
GL_FNC(_GL_1_3,void,glMultTransposeMatrixd,(const GLdouble *))
GL_FNC(_GL_1_3,void,glSampleCoverage,(GLclampf, GLboolean))
GL_FNC(_GL_1_3,void,glCompressedTexImage3D,(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *))
GL_FNC(_GL_1_3,void,glCompressedTexImage2D,(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *))
GL_FNC(_GL_1_3,void,glCompressedTexImage1D,(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *))
GL_FNC(_GL_1_3,void,glCompressedTexSubImage3D,(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *))
GL_FNC(_GL_1_3,void,glCompressedTexSubImage2D,(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *))
GL_FNC(_GL_1_3,void,glCompressedTexSubImage1D,(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *))
GL_FNC(_GL_1_3,void,glGetCompressedTexImage,(GLenum, GLint, GLvoid *))

/*-----------------------------------------------------------------------------
	Basic OpenGL 1.4 functions
-----------------------------------------------------------------------------*/

GL_EXT(_GL_1_4)
// GL 1.4
GL_FNC(_GL_1_4,void,glBlendFuncSeparate,(GLenum, GLenum, GLenum, GLenum))
GL_FNC(_GL_1_4,void,glFogCoordf,(GLfloat))
GL_FNC(_GL_1_4,void,glFogCoordfv,(const GLfloat *))
GL_FNC(_GL_1_4,void,glFogCoordd,(GLdouble))
GL_FNC(_GL_1_4,void,glFogCoorddv,(const GLdouble *))
GL_FNC(_GL_1_4,void,glFogCoordPointer,(GLenum, GLsizei, const GLvoid *))
GL_FNC(_GL_1_4,void,glMultiDrawArrays,(GLenum, GLint *, GLsizei *, GLsizei))
GL_FNC(_GL_1_4,void,glMultiDrawElements,(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei))
GL_FNC(_GL_1_4,void,glPointParameterf,(GLenum, GLfloat))
GL_FNC(_GL_1_4,void,glPointParameterfv,(GLenum, const GLfloat *))
GL_FNC(_GL_1_4,void,glPointParameteri,(GLenum, GLint))
GL_FNC(_GL_1_4,void,glPointParameteriv,(GLenum, const GLint *))
GL_FNC(_GL_1_4,void,glSecondaryColor3b,(GLbyte, GLbyte, GLbyte))
GL_FNC(_GL_1_4,void,glSecondaryColor3bv,(const GLbyte *))
GL_FNC(_GL_1_4,void,glSecondaryColor3d,(GLdouble, GLdouble, GLdouble))
GL_FNC(_GL_1_4,void,glSecondaryColor3dv,(const GLdouble *))
GL_FNC(_GL_1_4,void,glSecondaryColor3f,(GLfloat, GLfloat, GLfloat))
GL_FNC(_GL_1_4,void,glSecondaryColor3fv,(const GLfloat *))
GL_FNC(_GL_1_4,void,glSecondaryColor3i,(GLint, GLint, GLint))
GL_FNC(_GL_1_4,void,glSecondaryColor3iv,(const GLint *))
GL_FNC(_GL_1_4,void,glSecondaryColor3s,(GLshort, GLshort, GLshort))
GL_FNC(_GL_1_4,void,glSecondaryColor3sv,(const GLshort *))
GL_FNC(_GL_1_4,void,glSecondaryColor3ub,(GLubyte, GLubyte, GLubyte))
GL_FNC(_GL_1_4,void,glSecondaryColor3ubv,(const GLubyte *))
GL_FNC(_GL_1_4,void,glSecondaryColor3ui,(GLuint, GLuint, GLuint))
GL_FNC(_GL_1_4,void,glSecondaryColor3uiv,(const GLuint *))
GL_FNC(_GL_1_4,void,glSecondaryColor3us,(GLushort, GLushort, GLushort))
GL_FNC(_GL_1_4,void,glSecondaryColor3usv,(const GLushort *))
GL_FNC(_GL_1_4,void,glSecondaryColorPointer,(GLint, GLenum, GLsizei, const GLvoid *))
GL_FNC(_GL_1_4,void,glWindowPos2d,(GLdouble, GLdouble))
GL_FNC(_GL_1_4,void,glWindowPos2dv,(const GLdouble *))
GL_FNC(_GL_1_4,void,glWindowPos2f,(GLfloat, GLfloat))
GL_FNC(_GL_1_4,void,glWindowPos2fv,(const GLfloat *))
GL_FNC(_GL_1_4,void,glWindowPos2i,(GLint, GLint))
GL_FNC(_GL_1_4,void,glWindowPos2iv,(const GLint *))
GL_FNC(_GL_1_4,void,glWindowPos2s,(GLshort, GLshort))
GL_FNC(_GL_1_4,void,glWindowPos2sv,(const GLshort *))
GL_FNC(_GL_1_4,void,glWindowPos3d,(GLdouble, GLdouble, GLdouble))
GL_FNC(_GL_1_4,void,glWindowPos3dv,(const GLdouble *))
GL_FNC(_GL_1_4,void,glWindowPos3f,(GLfloat, GLfloat, GLfloat))
GL_FNC(_GL_1_4,void,glWindowPos3fv,(const GLfloat *))
GL_FNC(_GL_1_4,void,glWindowPos3i,(GLint, GLint, GLint))
GL_FNC(_GL_1_4,void,glWindowPos3iv,(const GLint *))
GL_FNC(_GL_1_4,void,glWindowPos3s,(GLshort, GLshort, GLshort))
GL_FNC(_GL_1_4,void,glWindowPos3sv,(const GLshort *))

/*-----------------------------------------------------------------------------
	Basic OpenGL 1.5 functions
-----------------------------------------------------------------------------*/

GL_EXT(_GL_1_5)
// GL 1.5
GL_FNC(_GL_1_5,void,glGenQueries,(GLsizei, GLuint *))
GL_FNC(_GL_1_5,void,glDeleteQueries,(GLsizei, const GLuint *))
GL_FNC(_GL_1_5,GLboolean,glIsQuery,(GLuint))
GL_FNC(_GL_1_5,void,glBeginQuery,(GLenum, GLuint))
GL_FNC(_GL_1_5,void,glEndQuery,(GLenum))
GL_FNC(_GL_1_5,void,glGetQueryiv,(GLenum, GLenum, GLint *))
GL_FNC(_GL_1_5,void,glGetQueryObjectiv,(GLuint, GLenum, GLint *))
GL_FNC(_GL_1_5,void,glGetQueryObjectuiv,(GLuint, GLenum, GLuint *))
GL_FNC(_GL_1_5,void,glBindBuffer,(GLenum, GLuint))
GL_FNC(_GL_1_5,void,glDeleteBuffers,(GLsizei, const GLuint *))
GL_FNC(_GL_1_5,void,glGenBuffers,(GLsizei, GLuint *))
GL_FNC(_GL_1_5,GLboolean,glIsBuffer,(GLuint))
GL_FNC(_GL_1_5,void,glBufferData,(GLenum, GLsizeiptr, const GLvoid *, GLenum))
GL_FNC(_GL_1_5,void,glBufferSubData,(GLenum, GLintptr, GLsizeiptr, const GLvoid *))
GL_FNC(_GL_1_5,void,glGetBufferSubData,(GLenum, GLintptr, GLsizeiptr, GLvoid *))
GL_FNC(_GL_1_5,GLvoid*,glMapBuffer,(GLenum, GLenum))
GL_FNC(_GL_1_5,GLboolean,glUnmapBuffer,(GLenum))
GL_FNC(_GL_1_5,void,glGetBufferParameteriv,(GLenum, GLenum, GLint *))
GL_FNC(_GL_1_5,void,glGetBufferPointerv,(GLenum, GLenum, GLvoid* *))

/*-----------------------------------------------------------------------------
	Basic OpenGL 2.0 functions
-----------------------------------------------------------------------------*/

GL_EXT(_GL_2_0)
// GL 2.0
GL_FNC(_GL_2_0,void,glBlendEquationSeparate,(GLenum, GLenum))
GL_FNC(_GL_2_0,void,glDrawBuffers,(GLsizei, const GLenum *))
GL_FNC(_GL_2_0,void,glStencilOpSeparate,(GLenum, GLenum, GLenum, GLenum))
GL_FNC(_GL_2_0,void,glStencilFuncSeparate,(GLenum, GLenum, GLint, GLuint))
GL_FNC(_GL_2_0,void,glStencilMaskSeparate,(GLenum, GLuint))
GL_FNC(_GL_2_0,void,glAttachShader,(GLuint, GLuint))
GL_FNC(_GL_2_0,void,glBindAttribLocation,(GLuint, GLuint, const GLchar *))
GL_FNC(_GL_2_0,void,glCompileShader,(GLuint))
GL_FNC(_GL_2_0,GLuint,glCreateProgram,(void))
GL_FNC(_GL_2_0,GLuint,glCreateShader,(GLenum))
GL_FNC(_GL_2_0,void,glDeleteProgram,(GLuint))
GL_FNC(_GL_2_0,void,glDeleteShader,(GLuint))
GL_FNC(_GL_2_0,void,glDetachShader,(GLuint, GLuint))
GL_FNC(_GL_2_0,void,glDisableVertexAttribArray,(GLuint))
GL_FNC(_GL_2_0,void,glEnableVertexAttribArray,(GLuint))
GL_FNC(_GL_2_0,void,glGetActiveAttrib,(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *))
GL_FNC(_GL_2_0,void,glGetActiveUniform,(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *))
GL_FNC(_GL_2_0,void,glGetAttachedShaders,(GLuint, GLsizei, GLsizei *, GLuint *))
GL_FNC(_GL_2_0,GLint,glGetAttribLocation,(GLuint, const GLchar *))
GL_FNC(_GL_2_0,void,glGetProgramiv,(GLuint, GLenum, GLint *))
GL_FNC(_GL_2_0,void,glGetProgramInfoLog,(GLuint, GLsizei, GLsizei *, GLchar *))
GL_FNC(_GL_2_0,void,glGetShaderiv,(GLuint, GLenum, GLint *))
GL_FNC(_GL_2_0,void,glGetShaderInfoLog,(GLuint, GLsizei, GLsizei *, GLchar *))
GL_FNC(_GL_2_0,void,glGetShaderSource,(GLuint, GLsizei, GLsizei *, GLchar *))
GL_FNC(_GL_2_0,GLint,glGetUniformLocation,(GLuint, const GLchar *))
GL_FNC(_GL_2_0,void,glGetUniformfv,(GLuint, GLint, GLfloat *))
GL_FNC(_GL_2_0,void,glGetUniformiv,(GLuint, GLint, GLint *))
GL_FNC(_GL_2_0,void,glGetVertexAttribdv,(GLuint, GLenum, GLdouble *))
GL_FNC(_GL_2_0,void,glGetVertexAttribfv,(GLuint, GLenum, GLfloat *))
GL_FNC(_GL_2_0,void,glGetVertexAttribiv,(GLuint, GLenum, GLint *))
GL_FNC(_GL_2_0,void,glGetVertexAttribPointerv,(GLuint, GLenum, GLvoid* *))
GL_FNC(_GL_2_0,GLboolean,glIsProgram,(GLuint))
GL_FNC(_GL_2_0,GLboolean,glIsShader,(GLuint))
GL_FNC(_GL_2_0,void,glLinkProgram,(GLuint))
GL_FNC(_GL_2_0,void,glShaderSource,(GLuint, GLsizei, const GLchar* *, const GLint *))
GL_FNC(_GL_2_0,void,glUseProgram,(GLuint))
GL_FNC(_GL_2_0,void,glUniform1f,(GLint, GLfloat))
GL_FNC(_GL_2_0,void,glUniform2f,(GLint, GLfloat, GLfloat))
GL_FNC(_GL_2_0,void,glUniform3f,(GLint, GLfloat, GLfloat, GLfloat))
GL_FNC(_GL_2_0,void,glUniform4f,(GLint, GLfloat, GLfloat, GLfloat, GLfloat))
GL_FNC(_GL_2_0,void,glUniform1i,(GLint, GLint))
GL_FNC(_GL_2_0,void,glUniform2i,(GLint, GLint, GLint))
GL_FNC(_GL_2_0,void,glUniform3i,(GLint, GLint, GLint, GLint))
GL_FNC(_GL_2_0,void,glUniform4i,(GLint, GLint, GLint, GLint, GLint))
GL_FNC(_GL_2_0,void,glUniform1fv,(GLint, GLsizei, const GLfloat *))
GL_FNC(_GL_2_0,void,glUniform2fv,(GLint, GLsizei, const GLfloat *))
GL_FNC(_GL_2_0,void,glUniform3fv,(GLint, GLsizei, const GLfloat *))
GL_FNC(_GL_2_0,void,glUniform4fv,(GLint, GLsizei, const GLfloat *))
GL_FNC(_GL_2_0,void,glUniform1iv,(GLint, GLsizei, const GLint *))
GL_FNC(_GL_2_0,void,glUniform2iv,(GLint, GLsizei, const GLint *))
GL_FNC(_GL_2_0,void,glUniform3iv,(GLint, GLsizei, const GLint *))
GL_FNC(_GL_2_0,void,glUniform4iv,(GLint, GLsizei, const GLint *))
GL_FNC(_GL_2_0,void,glUniformMatrix2fv,(GLint, GLsizei, GLboolean, const GLfloat *))
GL_FNC(_GL_2_0,void,glUniformMatrix3fv,(GLint, GLsizei, GLboolean, const GLfloat *))
GL_FNC(_GL_2_0,void,glUniformMatrix4fv,(GLint, GLsizei, GLboolean, const GLfloat *))
GL_FNC(_GL_2_0,void,glValidateProgram,(GLuint))
GL_FNC(_GL_2_0,void,glVertexAttrib1d,(GLuint, GLdouble))
GL_FNC(_GL_2_0,void,glVertexAttrib1dv,(GLuint, const GLdouble *))
GL_FNC(_GL_2_0,void,glVertexAttrib1f,(GLuint, GLfloat))
GL_FNC(_GL_2_0,void,glVertexAttrib1fv,(GLuint, const GLfloat *))
GL_FNC(_GL_2_0,void,glVertexAttrib1s,(GLuint, GLshort))
GL_FNC(_GL_2_0,void,glVertexAttrib1sv,(GLuint, const GLshort *))
GL_FNC(_GL_2_0,void,glVertexAttrib2d,(GLuint, GLdouble, GLdouble))
GL_FNC(_GL_2_0,void,glVertexAttrib2dv,(GLuint, const GLdouble *))
GL_FNC(_GL_2_0,void,glVertexAttrib2f,(GLuint, GLfloat, GLfloat))
GL_FNC(_GL_2_0,void,glVertexAttrib2fv,(GLuint, const GLfloat *))
GL_FNC(_GL_2_0,void,glVertexAttrib2s,(GLuint, GLshort, GLshort))
GL_FNC(_GL_2_0,void,glVertexAttrib2sv,(GLuint, const GLshort *))
GL_FNC(_GL_2_0,void,glVertexAttrib3d,(GLuint, GLdouble, GLdouble, GLdouble))
GL_FNC(_GL_2_0,void,glVertexAttrib3dv,(GLuint, const GLdouble *))
GL_FNC(_GL_2_0,void,glVertexAttrib3f,(GLuint, GLfloat, GLfloat, GLfloat))
GL_FNC(_GL_2_0,void,glVertexAttrib3fv,(GLuint, const GLfloat *))
GL_FNC(_GL_2_0,void,glVertexAttrib3s,(GLuint, GLshort, GLshort, GLshort))
GL_FNC(_GL_2_0,void,glVertexAttrib3sv,(GLuint, const GLshort *))
GL_FNC(_GL_2_0,void,glVertexAttrib4Nbv,(GLuint, const GLbyte *))
GL_FNC(_GL_2_0,void,glVertexAttrib4Niv,(GLuint, const GLint *))
GL_FNC(_GL_2_0,void,glVertexAttrib4Nsv,(GLuint, const GLshort *))
GL_FNC(_GL_2_0,void,glVertexAttrib4Nub,(GLuint, GLubyte, GLubyte, GLubyte, GLubyte))
GL_FNC(_GL_2_0,void,glVertexAttrib4Nubv,(GLuint, const GLubyte *))
GL_FNC(_GL_2_0,void,glVertexAttrib4Nuiv,(GLuint, const GLuint *))
GL_FNC(_GL_2_0,void,glVertexAttrib4Nusv,(GLuint, const GLushort *))
GL_FNC(_GL_2_0,void,glVertexAttrib4bv,(GLuint, const GLbyte *))
GL_FNC(_GL_2_0,void,glVertexAttrib4d,(GLuint, GLdouble, GLdouble, GLdouble, GLdouble))
GL_FNC(_GL_2_0,void,glVertexAttrib4dv,(GLuint, const GLdouble *))
GL_FNC(_GL_2_0,void,glVertexAttrib4f,(GLuint, GLfloat, GLfloat, GLfloat, GLfloat))
GL_FNC(_GL_2_0,void,glVertexAttrib4fv,(GLuint, const GLfloat *))
GL_FNC(_GL_2_0,void,glVertexAttrib4iv,(GLuint, const GLint *))
GL_FNC(_GL_2_0,void,glVertexAttrib4s,(GLuint, GLshort, GLshort, GLshort, GLshort))
GL_FNC(_GL_2_0,void,glVertexAttrib4sv,(GLuint, const GLshort *))
GL_FNC(_GL_2_0,void,glVertexAttrib4ubv,(GLuint, const GLubyte *))
GL_FNC(_GL_2_0,void,glVertexAttrib4uiv,(GLuint, const GLuint *))
GL_FNC(_GL_2_0,void,glVertexAttrib4usv,(GLuint, const GLushort *))
GL_FNC(_GL_2_0,void,glVertexAttribPointer,(GLuint, GLint, GLenum, GLboolean, GLsizei, const GLvoid *))


#ifdef WIN32
// WGL functions.
GL_FNC(_GL,BOOL,wglCopyContext,(HGLRC,HGLRC,UINT))
GL_FNC(_GL,HGLRC,wglCreateContext,(HDC))
GL_FNC(_GL,HGLRC,wglCreateLayerContext,(HGLRC))
GL_FNC(_GL,BOOL,wglDeleteContext,(HGLRC))
GL_FNC(_GL,HGLRC,wglGetCurrentContext,(VOID))
GL_FNC(_GL,HDC,wglGetCurrentDC,(VOID))
GL_FNC(_GL,PROC,wglGetProcAddress,(LPCSTR))
GL_FNC(_GL,BOOL,wglMakeCurrent,(HDC, HGLRC))
GL_FNC(_GL,BOOL,wglShareLists,(HGLRC,HGLRC))
GL_FNC(_GL,BOOL,wglUseFontBitmapsA,(HDC, DWORD, DWORD, DWORD))
GL_FNC(_GL,BOOL,wglUseFontBitmapsW,(HDC, DWORD, DWORD, DWORD))
// GDI functions. wrapped in opengl32.dll
GL_FNC(_GL,INT,wglChoosePixelFormat,(HDC hDC,CONST PIXELFORMATDESCRIPTOR*))
GL_FNC(_GL,INT,wglDescribePixelFormat,(HDC,INT,UINT,PIXELFORMATDESCRIPTOR*))
GL_FNC(_GL,BOOL,wglGetPixelFormat,(HDC))
GL_FNC(_GL,BOOL,wglSetPixelFormat,(HDC,INT,CONST PIXELFORMATDESCRIPTOR*))
GL_FNC(_GL,BOOL,wglSwapBuffers,(HDC hDC))
#endif


/*-----------------------------------------------------------------------------
	OpenGL extensions. have been improved to OpenGL core.
-----------------------------------------------------------------------------*/

/*
// GL 1.2, rescale normal
GL_EXT(_GL_EXT_rescale_normal)

// GL 1.2, texture3D
GL_EXT(_GL_EXT_texture3D)
GL_FNC(_GL_EXT_texture3D,void,glTexImage3DEXT,(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *))
GL_FNC(_GL_EXT_texture3D,void,glTexSubImage3DEXT,(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *))

// GL 1.2, edge clamp.
GL_EXT(_GL_EXT_texture_edge_clamp)

// GL 1.3, ARB multitexture. 
GL_EXT(_GL_ARB_multitexture)
GL_FNC(_GL_ARB_multitexture,void,glMultiTexCoord1fARB,(GLenum target,GLfloat))
GL_FNC(_GL_ARB_multitexture,void,glMultiTexCoord2fARB,(GLenum target,GLfloat,GLfloat))
GL_FNC(_GL_ARB_multitexture,void,glMultiTexCoord3fARB,(GLenum target,GLfloat,GLfloat,GLfloat))
GL_FNC(_GL_ARB_multitexture,void,glMultiTexCoord4fARB,(GLenum target,GLfloat,GLfloat,GLfloat,GLfloat))
GL_FNC(_GL_ARB_multitexture,void,glMultiTexCoord1fvARB,(GLenum target,GLfloat))
GL_FNC(_GL_ARB_multitexture,void,glMultiTexCoord2fvARB,(GLenum target,GLfloat,GLfloat))
GL_FNC(_GL_ARB_multitexture,void,glMultiTexCoord3fvARB,(GLenum target,GLfloat,GLfloat,GLfloat))
GL_FNC(_GL_ARB_multitexture,void,glMultiTexCoord4fvARB,(GLenum target,GLfloat,GLfloat,GLfloat,GLfloat))
GL_FNC(_GL_ARB_multitexture,void,glActiveTextureARB,(GLenum target))
GL_FNC(_GL_ARB_multitexture,void,glClientActiveTextureARB,(GLenum target))

// GL 1.3, Generic texture compression. 
GL_EXT(_GL_ARB_texture_compression)
GL_FNC(_GL_ARB_texture_compression,void,glCompressedTexSubImage2DARB,(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *))
GL_FNC(_GL_ARB_texture_compression,void,glCompressedTexImage2DARB,(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *))

// GL 1.3, texture env add.
GL_EXT(_GL_ARB_texture_env_add)

// GL 1.3, texture env combine.
GL_EXT(_GL_ARB_texture_env_combine)

// GL 1.3, Cubemaps. 
GL_EXT(_GL_ARB_texture_cube_map)

// GL 1.3, border clamp
GL_EXT(_GL_ARB_texture_border_clamp)

// GL 1.3, multisample
GL_EXT(_GL_ARB_multisample)
GL_FNC(_GL_ARB_multisample,void,glSampleCoverageARB,(GLclampf, GLboolean))

// GL 1.4
GL_EXT(_GL_EXT_texture_lod_bias)

// texture anisotropic filter
GL_EXT(_GL_EXT_texture_filter_anisotropic)

// GL 1.4, depth texture
GL_EXT(_GL_ARB_depth_texture)

// GL 1.4, shadow mapping
GL_EXT(_GL_ARB_shadow)

// GL 1.5, vertex buffer object
GL_EXT(_GL_ARB_vertex_buffer_object)
GL_FNC(_GL_ARB_vertex_buffer_object,void,glBindBufferARB,(GLenum target, GLuint buffer))
GL_FNC(_GL_ARB_vertex_buffer_object,void,glDeleteBuffersARB,(GLsizei n, const GLuint *buffers))
GL_FNC(_GL_ARB_vertex_buffer_object,void,glGenBuffersARB,(GLsizei n, GLuint *buffers))
GL_FNC(_GL_ARB_vertex_buffer_object,GLboolean,glIsBufferARB,(GLuint buffer))
GL_FNC(_GL_ARB_vertex_buffer_object,void,glBufferDataARB,(GLenum target, GLsizeiptrARB size, const void *data, GLenum usage))
GL_FNC(_GL_ARB_vertex_buffer_object,void,glBufferSubDataARB,(GLenum target, GLintptrARB offset, GLsizeiptrARB size, const void *data))
GL_FNC(_GL_ARB_vertex_buffer_object,void,glGetBufferSubDataARB,(GLenum target, GLintptrARB offset, GLsizeiptrARB size, void *data))
GL_FNC(_GL_ARB_vertex_buffer_object,void,glMapBufferARB,(GLenum target, GLenum access))
GL_FNC(_GL_ARB_vertex_buffer_object,GLboolean,glUnmapBufferARB,(GLenum target))
GL_FNC(_GL_ARB_vertex_buffer_object,void,glGetBufferParameterivARB,(GLenum target, GLenum pname, int *params))
GL_FNC(_GL_ARB_vertex_buffer_object,void,glGetBufferPointervARB,(GLenum target, GLenum pname, void **params))


// GL 2.0, shader objects
GL_EXT(_GL_ARB_shader_objects)
GL_FNC(_GL_ARB_shader_objects,void,glDeleteObjectARB,(GLhandleARB));
GL_FNC(_GL_ARB_shader_objects,GLhandleARB,glGetHandleARB,(GLenum));
GL_FNC(_GL_ARB_shader_objects,void,glDetachObjectARB,(GLhandleARB, GLhandleARB));
GL_FNC(_GL_ARB_shader_objects,GLhandleARB,glCreateShaderObjectARB,(GLenum));
GL_FNC(_GL_ARB_shader_objects,void,glShaderSourceARB,(GLhandleARB, GLsizei, const GLcharARB* *, const GLint *));
GL_FNC(_GL_ARB_shader_objects,void,glCompileShaderARB,(GLhandleARB));
GL_FNC(_GL_ARB_shader_objects,GLhandleARB,glCreateProgramObjectARB,(void));
GL_FNC(_GL_ARB_shader_objects,void,glAttachObjectARB,(GLhandleARB, GLhandleARB));
GL_FNC(_GL_ARB_shader_objects,void,glLinkProgramARB,(GLhandleARB));
GL_FNC(_GL_ARB_shader_objects,void,glUseProgramObjectARB,(GLhandleARB));
GL_FNC(_GL_ARB_shader_objects,void,glValidateProgramARB,(GLhandleARB));
GL_FNC(_GL_ARB_shader_objects,void,glUniform1fARB,(GLint, GLfloat));
GL_FNC(_GL_ARB_shader_objects,void,glUniform2fARB,(GLint, GLfloat, GLfloat));
GL_FNC(_GL_ARB_shader_objects,void,glUniform3fARB,(GLint, GLfloat, GLfloat, GLfloat));
GL_FNC(_GL_ARB_shader_objects,void,glUniform4fARB,(GLint, GLfloat, GLfloat, GLfloat, GLfloat));
GL_FNC(_GL_ARB_shader_objects,void,glUniform1iARB,(GLint, GLint));
GL_FNC(_GL_ARB_shader_objects,void,glUniform2iARB,(GLint, GLint, GLint));
GL_FNC(_GL_ARB_shader_objects,void,glUniform3iARB,(GLint, GLint, GLint, GLint));
GL_FNC(_GL_ARB_shader_objects,void,glUniform4iARB,(GLint, GLint, GLint, GLint, GLint));
GL_FNC(_GL_ARB_shader_objects,void,glUniform1fvARB,(GLint, GLsizei, const GLfloat *));
GL_FNC(_GL_ARB_shader_objects,void,glUniform2fvARB,(GLint, GLsizei, const GLfloat *));
GL_FNC(_GL_ARB_shader_objects,void,glUniform3fvARB,(GLint, GLsizei, const GLfloat *));
GL_FNC(_GL_ARB_shader_objects,void,glUniform4fvARB,(GLint, GLsizei, const GLfloat *));
GL_FNC(_GL_ARB_shader_objects,void,glUniform1ivARB,(GLint, GLsizei, const GLint *));
GL_FNC(_GL_ARB_shader_objects,void,glUniform2ivARB,(GLint, GLsizei, const GLint *));
GL_FNC(_GL_ARB_shader_objects,void,glUniform3ivARB,(GLint, GLsizei, const GLint *));
GL_FNC(_GL_ARB_shader_objects,void,glUniform4ivARB,(GLint, GLsizei, const GLint *));
GL_FNC(_GL_ARB_shader_objects,void,glUniformMatrix2fvARB,(GLint, GLsizei, GLboolean, const GLfloat *));
GL_FNC(_GL_ARB_shader_objects,void,glUniformMatrix3fvARB,(GLint, GLsizei, GLboolean, const GLfloat *));
GL_FNC(_GL_ARB_shader_objects,void,glUniformMatrix4fvARB,(GLint, GLsizei, GLboolean, const GLfloat *));
GL_FNC(_GL_ARB_shader_objects,void,glGetObjectParameterfvARB,(GLhandleARB, GLenum, GLfloat *));
GL_FNC(_GL_ARB_shader_objects,void,glGetObjectParameterivARB,(GLhandleARB, GLenum, GLint *));
GL_FNC(_GL_ARB_shader_objects,void,glGetInfoLogARB,(GLhandleARB, GLsizei, GLsizei *, GLcharARB *));
GL_FNC(_GL_ARB_shader_objects,void,glGetAttachedObjectsARB,(GLhandleARB, GLsizei, GLsizei *, GLhandleARB *));
GL_FNC(_GL_ARB_shader_objects,GLint,glGetUniformLocationARB,(GLhandleARB, const GLcharARB *));
GL_FNC(_GL_ARB_shader_objects,void,glGetActiveUniformARB,(GLhandleARB, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLcharARB *));
GL_FNC(_GL_ARB_shader_objects,void,glGetUniformfvARB,(GLhandleARB, GLint, GLfloat *));
GL_FNC(_GL_ARB_shader_objects,void,glGetUniformivARB,(GLhandleARB, GLint, GLint *));
GL_FNC(_GL_ARB_shader_objects,void,glGetShaderSourceARB,(GLhandleARB, GLsizei, GLsizei *, GLcharARB *));

// GL 2.0, GLslang vertex shader
GL_EXT(_GL_ARB_vertex_shader)
GL_FNC(_GL_ARB_vertex_shader,void,glBindAttribLocationARB,(GLhandleARB, GLuint, const GLcharARB *));
GL_FNC(_GL_ARB_vertex_shader,void,glGetActiveAttribARB,(GLhandleARB, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLcharARB *));
GL_FNC(_GL_ARB_vertex_shader,GLint,glGetAttribLocationARB,(GLhandleARB, const GLcharARB *));

// GL 2.0 GLslang fragment shader
GL_EXT(_GL_ARB_fragment_shader)

// GL 2.0, shading language
GL_EXT(_GL_ARB_shading_language_100)

*/


/*-----------------------------------------------------------------------------
	OpenGL extensions. not improved to OpenGL core.
-----------------------------------------------------------------------------*/

// DXTC
GL_EXT(_GL_EXT_texture_compression_s3tc)

// frame buffer object
GL_EXT(_GL_EXT_framebuffer_object)
GL_FNC(_GL_EXT_framebuffer_object,GLboolean,glIsRenderbufferEXT,(GLuint))
GL_FNC(_GL_EXT_framebuffer_object,void,glBindRenderbufferEXT,(GLenum, GLuint))
GL_FNC(_GL_EXT_framebuffer_object,void,glDeleteRenderbuffersEXT,(GLsizei, const GLuint *))
GL_FNC(_GL_EXT_framebuffer_object,void,glGenRenderbuffersEXT,(GLsizei, GLuint *))
GL_FNC(_GL_EXT_framebuffer_object,void,glRenderbufferStorageEXT,(GLenum, GLenum, GLsizei, GLsizei))
GL_FNC(_GL_EXT_framebuffer_object,void,glGetRenderbufferParameterivEXT,(GLenum, GLenum, GLint *))
GL_FNC(_GL_EXT_framebuffer_object,GLboolean,glIsFramebufferEXT,(GLuint))
GL_FNC(_GL_EXT_framebuffer_object,void,glBindFramebufferEXT,(GLenum, GLuint))
GL_FNC(_GL_EXT_framebuffer_object,void,glDeleteFramebuffersEXT,(GLsizei, const GLuint *))
GL_FNC(_GL_EXT_framebuffer_object,void,glGenFramebuffersEXT,(GLsizei, GLuint *))
GL_FNC(_GL_EXT_framebuffer_object,GLenum,glCheckFramebufferStatusEXT,(GLenum))
GL_FNC(_GL_EXT_framebuffer_object,void,glFramebufferTexture1DEXT,(GLenum, GLenum, GLenum, GLuint, GLint))
GL_FNC(_GL_EXT_framebuffer_object,void,glFramebufferTexture2DEXT,(GLenum, GLenum, GLenum, GLuint, GLint))
GL_FNC(_GL_EXT_framebuffer_object,void,glFramebufferTexture3DEXT,(GLenum, GLenum, GLenum, GLuint, GLint, GLint))
GL_FNC(_GL_EXT_framebuffer_object,void,glFramebufferRenderbufferEXT,(GLenum, GLenum, GLenum, GLuint))
GL_FNC(_GL_EXT_framebuffer_object,void,glGetFramebufferAttachmentParameterivEXT,(GLenum, GLenum, GLenum, GLint *))
GL_FNC(_GL_EXT_framebuffer_object,void,glGenerateMipmapEXT,(GLenum))

GL_EXT(_GL_EXT_framebuffer_blit)
GL_FNC(_GL_EXT_framebuffer_blit,void,glBlitFramebufferEXT, (GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLbitfield, GLenum))

GL_EXT(_GL_EXT_framebuffer_multisample)
GL_FNC(_GL_EXT_framebuffer_multisample,void,glRenderbufferStorageMultisampleEXT,(GLenum, GLsizei, GLenum, GLsizei, GLsizei))

// packed depth stencil
GL_EXT(_GL_EXT_packed_depth_stencil)

GL_EXT(_GL_EXT_depth_bounds_test)
GL_FNC(_GL_EXT_depth_bounds_test,void, glDepthBoundsEXT, (GLclampd, GLclampd))

//
// vertex program
GL_EXT(_GL_ARB_vertex_program)
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib1sARB,(GLuint index, GLshort x))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib1fARB,(GLuint index, GLfloat x))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib1dARB,(GLuint index, GLdouble x))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib2sARB,(GLuint index, GLshort x, GLshort y))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib2fARB,(GLuint index, GLfloat x, GLfloat y))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib2dARB,(GLuint index, GLdouble x, GLdouble y))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib3sARB,(GLuint index, GLshort x, GLshort y, GLshort z))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib3fARB,(GLuint index, GLfloat x, GLfloat y, GLfloat z))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib3dARB,(GLuint index, GLdouble x, GLdouble y, GLdouble z))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4sARB,(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4fARB,(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4dARB,(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4NubARB,(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib1svARB,(GLuint index, const GLshort *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib1fvARB,(GLuint index, const GLfloat *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib1dvARB,(GLuint index, const GLdouble *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib2svARB,(GLuint index, const GLshort *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib2fvARB,(GLuint index, const GLfloat *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib2dvARB,(GLuint index, const GLdouble *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib3svARB,(GLuint index, const GLshort *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib3fvARB,(GLuint index, const GLfloat *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib3dvARB,(GLuint index, const GLdouble *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4bvARB,(GLuint index, const GLbyte *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4svARB,(GLuint index, const GLshort *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4ivARB,(GLuint index, const GLint *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4ubvARB,(GLuint index, const GLubyte *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4usvARB,(GLuint index, const GLushort *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4uivARB,(GLuint index, const GLuint *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4fvARB,(GLuint index, const GLfloat *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4dvARB,(GLuint index, const GLdouble *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4NbvARB,(GLuint index, const GLbyte *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4NsvARB,(GLuint index, const GLshort *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4NivARB,(GLuint index, const GLint *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4NubvARB,(GLuint index, const GLubyte *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4NusvARB,(GLuint index, const GLushort *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttrib4NuivARB,(GLuint index, const GLuint *v))
GL_FNC(_GL_ARB_vertex_program,void,glVertexAttribPointerARB,(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer))
GL_FNC(_GL_ARB_vertex_program,void,glEnableVertexAttribArrayARB,(GLuint index))
GL_FNC(_GL_ARB_vertex_program,void,glDisableVertexAttribArrayARB,(GLuint index))
GL_FNC(_GL_ARB_vertex_program,void,glProgramStringARB,(GLenum target, GLenum format, GLsizei len, const void *string)) 
GL_FNC(_GL_ARB_vertex_program,void,glBindProgramARB,(GLenum target, GLuint program))
GL_FNC(_GL_ARB_vertex_program,void,glDeleteProgramsARB,(GLsizei n, const GLuint *programs))
GL_FNC(_GL_ARB_vertex_program,void,glGenProgramsARB,(GLsizei n, GLuint *programs))
GL_FNC(_GL_ARB_vertex_program,void,glProgramEnvParameter4dARB,(GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w))
GL_FNC(_GL_ARB_vertex_program,void,glProgramEnvParameter4dvARB,(GLenum target, GLuint index, const GLdouble *params))
GL_FNC(_GL_ARB_vertex_program,void,glProgramEnvParameter4fARB,(GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w))
GL_FNC(_GL_ARB_vertex_program,void,glProgramEnvParameter4fvARB,(GLenum target, GLuint index, const GLfloat *params))
GL_FNC(_GL_ARB_vertex_program,void,glProgramLocalParameter4dARB,(GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w))
GL_FNC(_GL_ARB_vertex_program,void,glProgramLocalParameter4dvARB,(GLenum target, GLuint index, const GLdouble *params))
GL_FNC(_GL_ARB_vertex_program,void,glProgramLocalParameter4fARB,(GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w))
GL_FNC(_GL_ARB_vertex_program,void,glProgramLocalParameter4fvARB,(GLenum target, GLuint index, const GLfloat *params))
GL_FNC(_GL_ARB_vertex_program,void,glGetProgramEnvParameterdvARB,(GLenum target, GLuint index, GLdouble *params))
GL_FNC(_GL_ARB_vertex_program,void,glGetProgramEnvParameterfvARB,(GLenum target, GLuint index, GLfloat *params))
GL_FNC(_GL_ARB_vertex_program,void,glGetProgramLocalParameterdvARB,(GLenum target, GLuint index, GLdouble *params))
GL_FNC(_GL_ARB_vertex_program,void,glGetProgramLocalParameterfvARB,(GLenum target, GLuint index, GLfloat *params))
GL_FNC(_GL_ARB_vertex_program,void,glGetProgramivARB,(GLenum target, GLenum pname, GLint *params))
GL_FNC(_GL_ARB_vertex_program,void,glGetProgramStringARB,(GLenum target, GLenum pname, void *string))
GL_FNC(_GL_ARB_vertex_program,void,glGetVertexAttribdvARB,(GLuint index, GLenum pname, GLdouble *params))
GL_FNC(_GL_ARB_vertex_program,void,glGetVertexAttribfvARB,(GLuint index, GLenum pname, GLfloat *params))
GL_FNC(_GL_ARB_vertex_program,void,glGetVertexAttribivARB,(GLuint index, GLenum pname, GLint *params))
GL_FNC(_GL_ARB_vertex_program,void,glGetVertexAttribPointervARB,(GLuint index, GLenum pname, void **pointer))
GL_FNC(_GL_ARB_vertex_program,GLboolean,glIsProgramARB,(GLuint program))

// fragment program
GL_EXT(_GL_ARB_fragment_program)

// fragment program with shadow mapping
GL_EXT(_GL_ARB_fragment_program_shadow)
//

// pixel buffer object
GL_EXT(_GL_EXT_pixel_buffer_object)

// rectangle texture
GL_EXT(_GL_ARB_texture_rectangle)

// float texture
GL_EXT(_GL_ARB_texture_float)

// float buffer
GL_EXT(_GL_ARB_color_buffer_float)
GL_FNC(_GL_ARB_color_buffer_float, void, glClampColorARB, (GLenum, GLenum))

// half float data type
GL_EXT(_GL_ARB_half_float_pixel)

/*-----------------------------------------------------------------------------
	OpenGL extensions. platform specified
-----------------------------------------------------------------------------*/


#ifdef _WIN32
// WGL extensions string
GL_EXT(_WGL_EXT_extensions_string)
GL_FNC(_WGL_EXT_extensions_string,const char *,wglGetExtensionsStringEXT,(void))

// WGL swap control
GL_EXT(_WGL_EXT_swap_control)
GL_FNC(_WGL_EXT_swap_control,BOOL,wglSwapIntervalEXT,(int))
GL_FNC(_WGL_EXT_swap_control,int,wglGetSwapIntervalEXT,(void))

/*

// WGL pixel format
GL_EXT(_WGL_ARB_pixel_format)
GL_FNC(_WGL_ARB_pixel_format,BOOL,wglGetPixelFormatAttribivARB,(HDC, int, int, UINT, const int *, int *))
GL_FNC(_WGL_ARB_pixel_format,BOOL,wglGetPixelFormatAttribfvARB,(HDC, int, int, UINT, const int *, FLOAT *))
GL_FNC(_WGL_ARB_pixel_format,BOOL,wglChoosePixelFormatARB,(HDC, const int *, const FLOAT *, UINT, int *, UINT *))

// WGL pbuffer
GL_EXT(_WGL_ARB_pbuffer)
GL_FNC(_WGL_ARB_pbuffer,HPBUFFERARB,wglCreatePbufferARB,(HDC, int, int, int, const int *))
GL_FNC(_WGL_ARB_pbuffer,HDC,wglGetPbufferDCARB,(HPBUFFERARB))
GL_FNC(_WGL_ARB_pbuffer,int,wglReleasePbufferDCARB,(HPBUFFERARB, HDC))
GL_FNC(_WGL_ARB_pbuffer,BOOL,wglDestroyPbufferARB,(HPBUFFERARB))
GL_FNC(_WGL_ARB_pbuffer,BOOL,wglQueryPbufferARB,(HPBUFFERARB, int, int *))

// WGL render to texture
GL_EXT(_WGL_ARB_render_texture)
GL_FNC(_WGL_ARB_render_texture,BOOL,wglBindTexImageARB,(HPBUFFERARB, int))
GL_FNC(_WGL_ARB_render_texture,BOOL,wglReleaseTexImageARB,(HPBUFFERARB, int))
GL_FNC(_WGL_ARB_render_texture,BOOL,wglSetPbufferAttribARB,(HPBUFFERARB, const int *))

// WGL render to depth texture
GL_EXT(_WGL_NV_render_depth_texture)
*/

#endif

