#ifndef AX_RENDER_SAMPLER_H
#define AX_RENDER_SAMPLER_H

AX_BEGIN_NAMESPACE

AX_DECLARE_REFPTR(SamplerState);
AX_DECLARE_REFPTR(BlendState);
AX_DECLARE_REFPTR(DepthStencilState);
AX_DECLARE_REFPTR(RasterizerState);

AX_END_NAMESPACE

#endif // AX_RENDER_SAMPLER_H
