#==============================================================================
# $Id: Makefile,v 1.1 2008/06/30 23:17:08 dunhill_hw Exp $
#
# Description:
# makefile for CxBase/Private
# just call parent directory's make
#
# History:
# * 2007/10/16 Created by Dunhill Hwang
#==============================================================================

# set top path first
TOP_PATH	:= ../..

all clean: 
	( cd .. && $(MAKE) $@ ) || exit 1;
